### ISSUE TITLE
Samples with the GridView usage

### ISSUE THREAD

**Issue by abrasat** [NobsterTheLobster/Xamarin.Forms.GridView#10]
Could you please add some samples with the usage of the GridView ?

**Comment by NobsterTheLobster** [comment]
They are already in the repo.

Xamarin.Forms.GridView/XamarinFormsGridView/XamarinFormsGridView/Views/Sample*.xaml

**Comment by abrasat** [comment]
I started the .Android application and only a white screen is displayed. Would be possible to move the samples in separate projects ?

**Comment by NobsterTheLobster** [comment]
Yeah that is actually my intention at some point. I've recently created a nugget project and so at some point I want to get the nugget project pushed into the repo and make the existing project in repo just for samples. 

However the last time I checked the current repo was entirely working. What version of xamarin.forms are you using. Its strange that you would getting a white screen but no errors.

**Comment by abrasat** [comment]
I am using Xamarin.Forms.2.3.5.239-pre3. In the PCL project file I had to replace the "C:\Output\..." references with relative paths. Are you planning to use a NET standard instead of PCL ?

**Comment by NobsterTheLobster** [comment]
Ah yes I was using a global folder for my nuget packages. I also see some C:\Output references in the android platform project for the compiled binaries as I was running into filename length issues. I will see about fixing those.

Moving away from PCL is not top of my list of priorities

By the way in-case you missed it, there is a section in the readme on what files are required so you can pick just the source files out of the repo and these are the only files that are included in the nuget package.

**Comment by abrasat** [comment]
I debugged the Android application, and it crashes at the InitializeComponent() call in the MasterDetailPage constructor. The ViewModel nevers gets created.

**Comment by NobsterTheLobster** [comment]
As far as I know (based on other comments) the repo worked fine for other people. Regardless I suggest you just create a new Xamarin forms project (PCL as opposed to shared) and just import only the files listed in the required files section.  That way you exclude any problems that is happening outside of the grid-view control.

Then create your own single simple view and view model as you would with any other project.  You can use the samples as a reference but I suggest you write your own.

**Comment by NobsterTheLobster** [comment]
The repo has been changed to separate the samples and control libraries.
