### ISSUE TITLE
Pull to refresh not working, and size of page will be incorrect if GridView is wrapped by ScrollView.

### ISSUE THREAD

**Issue by maxchu92** [NobsterTheLobster/Xamarin.Forms.GridView#11]
Hi, I tried your GridView. It is great and fast! And it is so much simpler than TwinTech. But I am having 2 issues.
1. The pull to refresh is not working for me.
2. When the GridView is wrapped by a ScrollView, the height of the page will become super long.

`#region Namespaces

//.NET
using System;
using System.Linq;
using System.Collections.Generic;
using System.Reflection;

//NuGet
using Xamarin.Forms;
using Plugin.GridViewControl.Common;
#endregion

namespace MyApp.Pages {
	public class PgGridView : ContentPage {
		public PgGridView () {
			Title = "Grid View";
			Content = new ScrollView{
				Content = Content = InitUI()
			};
		}

		protected override View InitUI() {
			var grdGridView = new GridView {
				IsGroupingEnabled = false,
				RowHeight = 130,
				MinItemWidth = 115,
				IsPullToRefreshEnabled = true,
				ItemsSource = InitListData(),
				ItemTemplate = new DataTemplate(BuildItemTemplate)
			};
			var cmdRefresh = new Command(async () => {
				await DisplayAlert("Refreshing", "List Refreshed!", "Woosh");
				grdGridView.EndRefresh();
			});
			var cmdTapped = new Command(async (object selectedItem) => {
				await DisplayAlert("Hello", "You tapped an item:" + (selectedItem as ColorData).Title, "Yup");
			});
			Grid.SetRow(grdGridView, 1);
			grdGridView.SetBinding(GridView.SelectedItemProperty, "SelectedItem", BindingMode.TwoWay);
			grdGridView.RefreshCommand = cmdRefresh;
			grdGridView.TappedCommand = cmdTapped;
			return grdGridView;
		}

		protected virtual Cell BuildItemTemplate() {
			var lblTitle = new Label {
				TextColor = Color.White,
				VerticalOptions = LayoutOptions.Fill
			};
			var pnlGrid = new GridLayout {
				Padding = new Thickness(10),
				Children = { lblTitle }
			};
			var cell = new GridViewXamlCell {
				View = pnlGrid
			};

			pnlGrid.SetBinding(Grid.BackgroundColorProperty, "Color");
			lblTitle.SetBinding(Label.TextProperty, "Title");

			return cell;
		}

		private List<ColorData> InitListData() {
			var lstData = new List<ColorData>();
			foreach (var obj in GetColorList()) {
				lstData.Add(new ColorData(obj.Key, obj.Value));
			}
			return lstData;
		}

		private Dictionary<string, Color> GetColorList() {
			var fields = typeof(Color).GetRuntimeFields().Where(FieldInfo => FieldInfo.IsPublic && FieldInfo.IsStatic && FieldInfo.FieldType == typeof(Color));
			return fields.ToDictionary(f => f.Name, f => (Color)f.GetValue(null));
		}

		private class ColorData {
			public string Title { get; set; }
			public Color Color { get; set; }
			public ColorData(string title, Color clr) {
				Title = title;
				Color = clr;
			}
		}
	}
}`

**Comment by NobsterTheLobster** [comment]
I'll have a look at hooking up pull to refresh with the ios and android renderers in the next release. Pull to refresh should be working for UWP.

Not sure on the layout issue. In my opinion its not the best design to have a scrollable itemscontrol inside a scrollviewer.

**Comment by maxchu92** [comment]
Agree. I had changed my page to not use the ScrollView. Looking forward to your update!

**Comment by NobsterTheLobster** [comment]
Pull to refresh added for Android. I'm looking at IOS now. Let me know if there are problems.

EDIT: Just to add the only real changes for application code were to the GridRenderer for Android. There are changes to the Sample1.xaml and Sample ViewModel.cs to demonstrate the feature.

**Comment by NobsterTheLobster** [comment]
iOS pull to refresh has been promoted.

**Comment by maxchu92** [comment]
Thanks! Keep up the good work! Tested on Android 6.0 and iOS 8.1 pull to refresh is working, but not working on Android 4.4.

**Comment by maxchu92** [comment]
Oh nevermind. I fixed it on Android 4.4, its the scrollview causing it not to work properly
