### ISSUE TITLE
SelectedItem is incorrect when grouping is enabled

### ISSUE THREAD

**Issue by CobraCalle** [NobsterTheLobster/Xamarin.Forms.GridView#13]
Hi,

when grouping is enabled the selected item is shifted 1 position.

When you select the first item, SelectedItem is null... when you select the second item, SelectedItem is the first item in the liste. Selecting the third item sets SelectedItem to the second item in list and so on.

Until now, I could only test this on Windows... will test in Android later

**Comment by CobraCalle** [comment]
Can not test is on Android... setting ItemsSource to null (while data is loading) results in ArgumentNullExpteion on Android. Windows UWP works fine

**Comment by NobsterTheLobster** [comment]
I'm getting some bizarre behaviours with testing my own demo. I'm getting multiple events firing for single clicks and its possibly leaking event handlers as well. I could have sworn everything worked correctly before. This issue could be down to changes\bugs in Xamarin.Forms https://bugzilla.xamarin.com/show_bug.cgi?id=60314

EDIT: Upgrading to xamarin.forms 2.5.*** fixes the multiple events firing but I'm still getting the issue you describe. I'm fairly confident though this is still something in the Xamarin.Forms framework.

**Comment by NobsterTheLobster** [comment]
Can you recheck this issue. I'm not seeing any problems with Xamarin.Forms 2.5.0.280555. I've uploaded some small tweaks to the renderer for the obsolete or deprecated elements in 2.5.0.280555.
