### ISSUE TITLE
Adding more than one GridView on on page throws ArgumentNull-Ex on Android

### ISSUE THREAD

**Issue by CobraCalle** [NobsterTheLobster/Xamarin.Forms.GridView#15]
I have a TabPage with two tabs. Each tab a GridView. That works fine on Windows (UWP), but on Android it throws an ArgumentNull-Ex.

Here is my XAML-Code:
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:views="clr-namespace:Diomex.XcalibuR.Configurator.Client.Xamarin.Views"
             xmlns:converters="clr-namespace:Diomex.XcalibuR.Configurator.Client.Xamarin.Converters"
             xmlns:gridView="clr-namespace:Plugin.GridViewControl.Common;assembly=Plugin.GridViewControl"
             x:Class="Diomex.XcalibuR.Configurator.Client.Xamarin.SelectProductPage">
    <ContentPage.Resources>
        <ResourceDictionary>
            <DataTemplate x:Key="defaultItemTemplate">
                <gridView:GridViewXamlCell>
                    <Grid Margin="3">
                        <Grid.RowDefinitions>
                            <RowDefinition Height="*"/>
                            <RowDefinition Height="50"/>
                        </Grid.RowDefinitions>
                        <views:ComposedImageView Grid.Row="0" Grid.RowSpan="2" ComposedImageVersion="{Binding MainImage.Max300x300}" VerticalOptions="Fill" HorizontalOptions="Fill"/>
                        <BoxView Grid.Row="1" BackgroundColor="LightBlue" Opacity="0.6"/>
                        <Label Grid.Row="1" Text="{Binding Name}" Margin="5" VerticalTextAlignment="Center" HorizontalOptions="Center"/>
                    </Grid>
                </gridView:GridViewXamlCell>
            </DataTemplate>
            <converters:IEnumerableToCollectionConverter x:Key="iEnumerableToCollectionConverter"/>
        </ResourceDictionary>
    </ContentPage.Resources>
    <ContentPage x:Name="pgSuppliers" Title="Lieferant">
        <gridView:GridView x:Name="lvSuppliers" RowHeight="200" MinItemWidth="200" IsPullToRefreshEnabled="False" ItemTemplate="{StaticResource defaultItemTemplate}" ItemsSource="{Binding Configuration.Suppliers}" SelectedItem="{Binding SelectedSupplier, Mode=TwoWay}" ItemSelected="lvSuppliers_ItemSelected"/>
    </ContentPage>
    <ContentPage x:Name="pgCatalogs" Title="Katalog">
        <gridView:GridView x:Name="lvCatalogs" RowHeight="200" MinItemWidth="200" IsPullToRefreshEnabled="False" ItemTemplate="{StaticResource defaultItemTemplate}" ItemsSource="{Binding SelectedSupplier.Catalogs}" SelectedItem="{Binding SelectedCatalog, Mode=TwoWay}" ItemSelected="lvCatalogs_ItemSelected"/>
    </ContentPage>
</TabbedPage>

Even when i remove the ItemsSource- and SelectedItem-Binding on the second GridView is will result in an ArgumentNull-Ex. When I remove the second GridView it works fine

**Comment by NobsterTheLobster** [comment]
I'm afraid I can't reproduce this. Multiple grid-view controls on a single content page or individually on multiple tabs works just fine for me. As does defining the data-template as a resource.

If you have any stack trace to go along with the error then feel free to create a new issue.
