### ISSUE TITLE
drawable statelist_item_background.xml causes griditems to vanish

### ISSUE THREAD

**Issue by RagBuster** [NobsterTheLobster/Xamarin.Forms.GridView#20]
I added the drawable statelist_item_background.xml used in the repo to the drawable folder but after doing this I now do not see any grid items render. Any ideas?

**Comment by NobsterTheLobster** [comment]
If its exact one from the repo then I've no idea. It works fine for me. Make sure your on the latest Xamarin forms stable.

**Comment by RagBuster** [comment]
Latest Xamarin forms already installed, I will continue investigation.

**Comment by RagBuster** [comment]
Found a fix, I failed to supply a rowheight parameter which has now fixed it.
