### ISSUE TITLE
[UWP]: too narrow a grid crashes

### ISSUE THREAD

**Issue by deakjahn** [NobsterTheLobster/Xamarin.Forms.GridView#21]
If the width of the grid view is brought below the minimum item width on UWP, it results in a "COMException: Error HRESULT E_FAIL has been returned from a call to a COM component" error.

The last line of the UWP renderer should be modified:

    itemsPanel.ItemWidth = Math.Min(total, total / canBeFit);

**Comment by NobsterTheLobster** [comment]
New version
