### ISSUE TITLE
Open source license missing

### ISSUE THREAD

**Issue by zgramana** [NobsterTheLobster/Xamarin.Forms.GridView#25]
There is no explicit grant of license to use or modify, so this isn't actually open source. Would be great if you added MIT or Apache 2.0 license so that people can fork and send you a PR. :)

**Comment by NobsterTheLobster** [comment]
Which licence do you prefer. My opinion is that a lack of a licence does not stop people forking and sending pull requests though. Both of those things have already happened.

**Comment by kipters** [comment]
I'd suggest using the MIT license, it's one of the most balanced ones: https://opensource.org/licenses/MIT

**Comment by zgramana** [comment]
I would recommend MIT or Apache 2.0. Both allow for commercial use, which most Xamarin.Forms projects are. Thanks!

**Comment by zgramana** [comment]
Also, Github created this tool to help developers select a license: 
https://choosealicense.com/
