### ISSUE TITLE
"IsPullToRefreshEnabled" and "IsRefreshing" 

### ISSUE THREAD

**Issue by devinZhou102** [NobsterTheLobster/Xamarin.Forms.GridView#26]
There are some problems while using "IsPullToRefreshEnabled" and "IsRefreshing",
"IsPullToRefreshEnabled" not work 
"IsRefreshing" not work well with Binding mode OneWay

**Comment by NobsterTheLobster** [comment]
#27 

Is this fixed by above. Can it be closed?
