### ISSUE TITLE
selected item visual for android 

### ISSUE THREAD

**Issue by repthor** [NobsterTheLobster/Xamarin.Forms.GridView#3]
If the selected item scrolls out of sight, some other (random?) item is rendered the selected way. 
If you scroll back - a random item is rendered selected - not the really selected one.

Under iOS everything works fine.

I guess, it could have to deal with RecyclerView. But Im a bloody beginner in app developement.

But you are a great helper for me NobsterTheLobster! Thank You very much!

**Comment by NobsterTheLobster** [comment]
Yeah I see what you mean and I think your right that its down to the recycler doing its thing. I'm trying to remember the selected view but since views are recycled I think I need to remember the selected position.

**Comment by NobsterTheLobster** [comment]
Ok I've promoted a fix. In the process of making this fix I've changed from using the Activated Property to the more appropriate Selected property (which I didn't even realised existed) so the drawable changed slightly as well.
