### ISSUE TITLE
Crash in Android

### ISSUE THREAD

**Issue by devperson** [NobsterTheLobster/Xamarin.Forms.GridView#33]
In some cases I get ORN exception in GridViewAdapter in ItemCount property. The solution is to make sure you check Items is not null so I suggest you to change following code from:
 
       public override int ItemCount
        {
            get
            {  
                return _flattenedItems != null ?  _flattenedItems.Count() : Items.Cast<object>().Count();
            }
        }

To 

    public override int ItemCount
        {
            get
            {
                if (_flattenedItems != null)
                    return _flattenedItems.Count();
                else if (Items != null)
                    return Items.Cast<object>().Count();
                else
                    return 0;
            }
        }

Note above ItemCount property located in GridViewAdapter class

**Comment by NobsterTheLobster** [comment]
#32
