### ISSUE TITLE
Cannot find statelist_item_background.xib 

### ISSUE THREAD

**Issue by pmatrasc** [NobsterTheLobster/Xamarin.Forms.GridView#36]
Hi,

I'm trying to follow the iOS instructions:

>  So currently you need to manually add the statelist_item_background.xib from the repo to your ios project.

Problem is that I cannot find this file (statelist_item_background.xib) anywhere.

Thanks.

**Comment by NobsterTheLobster** [comment]
Xamarin.Forms.GridView/XamarinFormsGridView/XamarinFormsGridView.iOS/statelist_item_background.xib 

Add it to your IOS project. 

Sorry I need to figure out how best to manage this.

**Comment by pmatrasc** [comment]
Thanks!
