### ISSUE TITLE
Is this code in Nuget?

### ISSUE THREAD

**Issue by fmeneuhe** [NobsterTheLobster/Xamarin.Forms.GridView#6]
Hi,
Is this code in Nuget?
Thanks

**Comment by NobsterTheLobster** [comment]
Sorry for the delay. No its not but that's actually something I've been thinking about. Its definitely something I want to get done.

EDIT: Further apologies on the delay. 8 Days! need to figure out what's going on with git notifications.

**Comment by NobsterTheLobster** [comment]
Install-Package Plugin.GridViewControl
